name: HTML-CSS-validation
run-name: Checking HTML on ${{ github.ref_name }} by ${{ github.actor }} 
on: [push]
jobs:
  Validate-HTML-CSS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HTML Validation 
        id: validation
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./
          css: true
        continue-on-error: true
      - name: Save Logs 
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log
      - name: Set Message
        id: errorMessage
        run : |
            cat log.log > $GITHUB_STEP_SUMMARY
      - name: Set info 
        run: |
            cat log.log | sed -e 's/file:/file=/' | sed -E 's/"(.*)":([0-9]+).([0-9]+)-([0-9]+).([0-9]+): ([^:]*):/::\6 \1,line=\2,endLine=\4,col=\3,endColumn=\5,title=\6::/' | sed -e 's/\/github\/workspace\/.\///g'
      - name: Fail on Invalid HTML/CSS
        if: ${{ steps.validation.outputs.result > 0 }}
        run: exit 1